name: ru_legal_assistant
description: "Юридический помощник по российскому праву. Работает оффлайн, без интернета. Поддержка УК РФ, КоАП, ГК РФ и Конституции."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  flutter_tts: ^4.2.3
  speech_to_text: ^6.5.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  get_it: ^7.7.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  analyzer: 6.4.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/laws/
    - assets/images/
    - assets/audio/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
